sudo: false
language: node_js
node_js:
  - 8
  - 9
  - node
  
os:
  - osx
  
before_install:
  - npm set progress=false
  - mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3"
  - mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins"
  - /usr/bin/defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist AlwaysReloadScript -bool YES

script:
  - npm install -g skpm
  - skpm create sketch-plugin-typescript --template=romansp/skpm-typescript
  - cd sketch-plugin-typescript
  - npm install
  - export NODE_ENV=production
  - npm run build
